
services:
    - docker
before_install:
    - docker build -t svetab/react -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true svetab/react npm test

after_success:
    - docker build -t svetab/multi-client ./client
    - docker build -t svetab/multi-nginx ./nginx
    - docker build -t svetab/multi-server ./server
    - docker build -t svetab/multi-worker ./worker
# Log in Docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push svetab/multi-client
    - docker push svetab/multi-server
    - docker push svetab/multi-nginx
    - docker push svetab/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-3
    app: docker-multi
    env: DockerMulti-env
    bucket_name: elasticbeanstalk-eu-west-3-149383739282
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY